name: CI Pipeline

# This workflow will be triggered on pushes to the 'main' branch
on:
  push:
    branches:
      - main

# Define environment variables that will be used across jobs
env:
  # The name of your Docker image in GitHub Packages
  IMAGE_NAME: ${{ github.repository }}
  # The name of your JAR file from your pom.xml
  JAR_FILE: booknest-0.0.1-SNAPSHOT.jar

jobs:
  # Job 1: Build and Test the Java Application
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Upload the JAR file as an artifact for the next job
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: booknest-jar
          path: target/${{ env.JAR_FILE }}

  # Job 2: Build and Push the Docker Image
  push-image:
    name: Build & Push Docker Image
    needs: build # This job will only run if the 'build' job succeeds
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Grant permission to push to GitHub Packages
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download JAR from previous job
        uses: actions/download-artifact@v4
        with:
          name: booknest-jar
          path: target

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:latest